"""Enumerations defined by docs/spec/02-agent-contracts.md."""

from __future__ import annotations

from enum import StrEnum


class UserRole(StrEnum):
    USER = "USER"
    AGENT = "AGENT"


class IntakeCompleteness(StrEnum):
    COMPLETE = "COMPLETE"
    INCOMPLETE = "INCOMPLETE"


class ResolutionAction(StrEnum):
    DECLINE = "DECLINE"
    FULL_REFUND = "FULL_REFUND"


class ReasonCode(StrEnum):
    ITEM_DAMAGED = "ITEM_DAMAGED"
    ITEM_NOT_AS_DESCRIBED = "ITEM_NOT_AS_DESCRIBED"
    MISSING_ITEM = "MISSING_ITEM"
    WRONG_ITEM = "WRONG_ITEM"
    QUALITY_ISSUE = "QUALITY_ISSUE"
    CHANGED_MIND = "CHANGED_MIND"


class RequestedAction(StrEnum):
    REFUND = "REFUND"
    RETURN_AND_REFUND = "RETURN_AND_REFUND"
    EXCHANGE = "EXCHANGE"
    UNSPECIFIED = "UNSPECIFIED"


class WaivedReturnReasonCode(StrEnum):
    ITEM_NOT_RECEIVED = "ITEM_NOT_RECEIVED"
    ITEM_UNSALVAGEABLE = "ITEM_UNSALVAGEABLE"
    HYGIENE_RISK = "HYGIENE_RISK"
    RETURN_UNECONOMICAL = "RETURN_UNECONOMICAL"
    EVIDENCE_SUFFICIENT_WITHOUT_RETURN = "EVIDENCE_SUFFICIENT_WITHOUT_RETURN"


class RequiredReturnReasonCode(StrEnum):
    POLICY_RETURN_REQUIRED = "POLICY_RETURN_REQUIRED"
    RESALE_VALUE_RETAINED = "RESALE_VALUE_RETAINED"
    RETURN_REQUIRED_FOR_INSPECTION = "RETURN_REQUIRED_FOR_INSPECTION"


class ReturnDecisionSource(StrEnum):
    POLICY = "POLICY"
    MODEL_JUDGMENT = "MODEL_JUDGMENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class ReturnPolicy(StrEnum):
    REQUIRED = "REQUIRED"
    NOT_REQUIRED = "NOT_REQUIRED"
    MODEL_JUDGMENT = "MODEL_JUDGMENT"


class EvidenceStatus(StrEnum):
    SUFFICIENT_FOR_APPROVAL = "SUFFICIENT_FOR_APPROVAL"
    SUFFICIENT_FOR_DECLINE = "SUFFICIENT_FOR_DECLINE"
    INSUFFICIENT = "INSUFFICIENT"


class ClaimStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    CONTRADICTED = "CONTRADICTED"


class EvidenceType(StrEnum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    TEXT = "TEXT"
    DOCUMENT = "DOCUMENT"


class EvidenceSource(StrEnum):
    USER = "USER"
    ORDER_TOOL = "ORDER_TOOL"
    LOGISTICS_TOOL = "LOGISTICS_TOOL"
    SYSTEM = "SYSTEM"


class SubjectScope(StrEnum):
    ORDER = "ORDER"
    LINE_ITEM = "LINE_ITEM"


class SatisfiableBy(StrEnum):
    SYSTEM_FACTS = "SYSTEM_FACTS"
    USER_EVIDENCE = "USER_EVIDENCE"


class ClaimId(StrEnum):
    ITEM_CONFIRMED_UNDELIVERED = "ITEM_CONFIRMED_UNDELIVERED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    ORDER_WITHIN_RETURN_WINDOW = "ORDER_WITHIN_RETURN_WINDOW"
    SHIPMENT_SEAL_INTACT = "SHIPMENT_SEAL_INTACT"
    ITEM_PHYSICALLY_DAMAGED = "ITEM_PHYSICALLY_DAMAGED"
    DAMAGE_PRESENT_ON_ARRIVAL = "DAMAGE_PRESENT_ON_ARRIVAL"
    ITEM_FUNCTIONALLY_IMPAIRED = "ITEM_FUNCTIONALLY_IMPAIRED"
    ITEM_DIFFERS_FROM_LISTING = "ITEM_DIFFERS_FROM_LISTING"
    WRONG_ITEM_RECEIVED = "WRONG_ITEM_RECEIVED"
    ITEM_NOT_IN_SHIPMENT = "ITEM_NOT_IN_SHIPMENT"
    ITEM_UNUSED = "ITEM_UNUSED"


class RetrievalStatus(StrEnum):
    OK = "OK"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_FOUND = "NOT_FOUND"


class VerificationStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNAVAILABLE = "UNAVAILABLE"


class ReviewVerdict(StrEnum):
    APPROVE = "APPROVE"
    REVISE = "REVISE"


class RevisionReasonCode(StrEnum):
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    POLICY_MISMATCH = "POLICY_MISMATCH"
    DECISION_UNSUPPORTED = "DECISION_UNSUPPORTED"
    DECISION_INCONSISTENT = "DECISION_INCONSISTENT"
    SCOPE_UNSUPPORTED = "SCOPE_UNSUPPORTED"
    RETURN_REQUIREMENT_INCONSISTENT = "RETURN_REQUIREMENT_INCONSISTENT"
    HANDOFF_INCOMPLETE = "HANDOFF_INCOMPLETE"
    OTHER = "OTHER"


class HumanDecision(StrEnum):
    APPROVE = "APPROVE"
    EDIT = "EDIT"
    REJECT = "REJECT"


class HumanCorrectionReasonCode(StrEnum):
    CLAIM_NOT_ESTABLISHED = "CLAIM_NOT_ESTABLISHED"
    POLICY_MISAPPLIED = "POLICY_MISAPPLIED"
    SCOPE_INCORRECT = "SCOPE_INCORRECT"
    RETURN_REQUIREMENT_INCORRECT = "RETURN_REQUIREMENT_INCORRECT"
    OTHER = "OTHER"


class OutcomeSource(StrEnum):
    REVIEWER_APPROVE = "REVIEWER_APPROVE"
    HUMAN_APPROVE = "HUMAN_APPROVE"
    HUMAN_EDIT = "HUMAN_EDIT"
    HUMAN_REJECT = "HUMAN_REJECT"


class EscalationReason(StrEnum):
    SPECIALIST_REQUIRED = "SPECIALIST_REQUIRED"
    POLICY_CONFIRMATION_DECLINED = "POLICY_CONFIRMATION_DECLINED"
    CLARIFICATION_BUDGET_EXCEEDED = "CLARIFICATION_BUDGET_EXCEEDED"
    EVIDENCE_BUDGET_EXCEEDED = "EVIDENCE_BUDGET_EXCEEDED"
    VERIFICATION_BUDGET_EXCEEDED = "VERIFICATION_BUDGET_EXCEEDED"
    REVISION_BUDGET_EXCEEDED = "REVISION_BUDGET_EXCEEDED"
    PROPOSE_BUDGET_EXCEEDED = "PROPOSE_BUDGET_EXCEEDED"
    VERIFICATION_UNAVAILABLE = "VERIFICATION_UNAVAILABLE"
    POLICY_AMBIGUOUS = "POLICY_AMBIGUOUS"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    CONFLICTING_REVISIONS = "CONFLICTING_REVISIONS"
    CONTRACT_VIOLATION = "CONTRACT_VIOLATION"


class ResolverResultType(StrEnum):
    DRAFT = "DRAFT"
    REQUEST_EVIDENCE = "REQUEST_EVIDENCE"
    CONFLICTING_REVISIONS = "CONFLICTING_REVISIONS"


class MemoryDistillationResultType(StrEnum):
    CREATE_CANDIDATE = "CREATE_CANDIDATE"
    SKIP = "SKIP"


class MemoryStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    APPROVED = "APPROVED"
    RETIRED = "RETIRED"


class RefundExecutionStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    REJECTED = "REJECTED"


class RefundApplicationStatus(StrEnum):
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"


class MemorySkipReasonCode(StrEnum):
    NO_FINAL_OUTCOME = "NO_FINAL_OUTCOME"
    CASE_SPECIFIC_ONLY = "CASE_SPECIFIC_ONLY"
    DATA_ENTRY_ERROR = "DATA_ENTRY_ERROR"
    POLICY_VERSION_UNKNOWN = "POLICY_VERSION_UNKNOWN"
    CLAIM_REGISTRY_VERSION_UNKNOWN = "CLAIM_REGISTRY_VERSION_UNKNOWN"
    RESTATES_EXISTING_POLICY = "RESTATES_EXISTING_POLICY"
    CONFLICTS_WITH_POLICY = "CONFLICTS_WITH_POLICY"
    NO_CONFIRMED_GENERALIZABLE_CORRECTION = "NO_CONFIRMED_GENERALIZABLE_CORRECTION"
